#!/bin/bash

sudo apt -y install libxss1 libappindicator1 libindicator7
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome*.deb

if [[ $? != 0 ]]; then
    # Fix missing
    sudo apt-get install -f
fi

rm -f google-chrome-stable_current_amd64.deb
