#!/bin/bash

scriptpath="$(dirname ${BASH_SOURCE[0]})"

if [[ $scriptpath == "." ]]; then
    scriptpath=$(pwd)
fi

# Dotfiles should not start with dots
function linkToHome() {
    path=$1
    name=$(basename $path)

    ln -s $scriptpath/$path ~/.$name > /dev/null 2>&1

    if [ $? -eq 0 ]; then
        echo "Linked $name"
    else
        echo "Skipping linking $name"
    fi
}

function linkDirToHome() {
    dir_path=$1
    name=$(basename $dir_path)

    if [ ! -d ~/.$name ]; then
        ln -s $scriptpath/${dir_path} ~/.$name > /dev/null 2>&1
        echo "Linked .${name} directory"
    else
        echo "Skipping linking .${name} directory"
    fi
}

function tryMakeDir() {
    dir_path=$1
    name=$(basename $dir_path)

    mkdir $dir_path > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo "Created $dir_path"
    else
        echo "Skipping creation of $dir_path directory"
    fi
}

########################################################
########################################################
########################################################

tryMakeDir "$HOME/.usr"
tryMakeDir "$HOME/.usr/bin"
tryMakeDir "$HOME/.usr/lib"

linkToHome "zsh/zshrc"
linkToHome "zsh/zpreztorc"
linkToHome "zsh/zprofile"
linkToHome "zsh/zshenv"
linkToHome "zsh/zlogin"
linkToHome "zsh/zlogout"

linkToHome "tmux.conf"
linkToHome "gdbinit"


linkToHome "gitignore"
if [[ $OSTYPE == darwin* ]]; then
    linkToHome "apple_git/gitconfig"
else
    linkToHome "ubuntu_git/gitconfig"
fi

linkToHome "vimrc"
linkDirToHome "vim"
linkDirToHome "ipython"
