#!/bin/bash

scriptpath="$(dirname ${BASH_SOURCE[0]})"

if [[ $scriptpath == "." ]]; then
    scriptpath=$(pwd)
fi

# Dotfiles should not start with dots
function linkToHome() {
    path=$1
    name=$(basename $path)

    ln -s $scriptpath/$path ~/.$name > /dev/null 2>&1

    if [ $? -eq 0 ]; then
        echo "Linked $name"
    else
        echo "Skipping linking $name"
    fi
}

########################################################
########################################################


linkToHome "zsh/zshrc"
linkToHome "zsh/zpreztorc"
linkToHome "zsh/zprofile"
linkToHome "zsh/zshenv"
linkToHome "zsh/zlogin"
linkToHome "zsh/zlogout"

#ln -s $scriptpath/custom ~/.oh-my-zsh > /dev/null 2>&1

#if [ $? -eq 0 ]; then
#    echo 'Linked custom to ~/.oh-my-zsh'
#else
#    echo 'Skipping linking custom to ~/.oh-my-zsh'
#fi

########################################################

#ln -s $scriptpath/zsh/zshrc ~/.zshrc > /dev/null 2>&1

#if [ $? -eq 0 ]; then
#    echo 'Linked zshrc'
#else
#    echo 'Skipping linking zshrc'
#fi

#########################################################

ln -s $scriptpath/gitconfig ~/.gitconfig > /dev/null 2>&1

if [ $? -eq 0 ]; then
    echo 'Created global .gitconfig'
else
    echo 'Skipping global .gitconfig'
fi

########################################################

ln -s $scriptpath/gitignore ~/.gitignore > /dev/null 2>&1

if [ $? -eq 0 ]; then
    echo 'Created global .gitignore'
else
    echo 'Skipping global .gitignore'
fi

########################################################

ln -s $scriptpath/vimrc ~/.vimrc > /dev/null 2>&1

if [ $? -eq 0 ]; then
    echo 'Created .vimrc'
else
    echo 'Skipping .vimrc'
fi

########################################################

if [ ! -d ~/.vim ]; then
    ln -s $scriptpath/vim ~/.vim > /dev/null 2>&1
    echo 'Created .vim directory'
else
    echo 'Skipping .vim directory'
fi

########################################################

mkdir ~/.bin > /dev/null 2>&1

if [ $? -eq 0 ]; then
    echo 'Creating ~/.bin'
else
    echo 'Skipping creation of ~/.bin'
fi
