#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

BASE_DIR=$(basename $SCRIPTPATH)

if [ "$SCRIPTPATH" != "${HOME}/.sys-config" ]; then
    echo "Move this folder to ~/.sys-config"
    exit 1
fi

# Link Dotfiles
$SCRIPTPATH/create-links

# Install necessary things
sudo apt update
sudo apt install -y build-essential
sudo apt install -y git
sudo apt install -y tig
sudo apt install -y vim
sudo apt install -y zsh
sudo apt install -y tmuxinator
sudo apt install -y terminator

# Install prezto
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${HOME}/.zprezto"
chsh -s /bin/zsh


# Finally do an upgrade (Done last since it takes some time)
sudo apt upgrade
