#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

BASE_DIR=$(basename $SCRIPTPATH)

if [ "$SCRIPTPATH" != "${HOME}/.sys-config" ]; then
    echo "Move this folder to ~/.sys-config"
    exit 1
fi

# Link Dotfiles
$SCRIPTPATH/create-links

# Install necessary things
$SCRIPTPATH/default-install-ubuntu

# Install prezto
git clone --recursive https://github.com/zsh-users/prezto.git "${HOME}/.zprezto"
chsh -s /bin/zsh


# Finally do an upgrade (Done last since it takes some time)
sudo apt upgrade

$SCRIPTPATH/chrome-install-ubuntu
