#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source ~/.sys-config/zsh/config/alias.zsh

if [[ "$OSTYPE" == linux* ]]; then
    source ~/.sys-config/zsh/config/ubuntu_alias.zsh
fi


if [[ "$OSTYPE" == darwin* ]]; then
    source ~/.sys-config/zsh/config/apple_alias.zsh

    # Load Z
    . /usr/local/Cellar/z/1.9/etc/profile.d/z.sh

    # OCaml OPAM configuration
    . /Users/connor/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
fi

# Allow typing 'dir' to translate to 'cd dir'
setopt AUTO_CD

# Disable the prompt asking to correct commands from zsh
unsetopt correct
