#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#

source $HOME/.zprofile

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#Initialize fasd if it's installed
command -v fasd >/dev/null 2>&1
if [ $? -eq 0 ] ; then
	eval "$(fasd --init auto)"
fi

source ~/.sys-config/zsh/config/alias.zsh

if [[ "$OSTYPE" == linux* ]]; then
    source ~/.sys-config/zsh/config/ubuntu_alias.zsh
	alias pac="pacaur"
fi


if [[ "$OSTYPE" == darwin* ]]; then
    source ~/.sys-config/zsh/config/apple_alias.zsh

    # OCaml OPAM configuration
    . /Users/connor/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
fi

# Allow typing 'dir' to translate to 'cd dir'
setopt AUTO_CD

# Disable the prompt asking to correct commands from zsh
unsetopt correct

